// File generated by flutterfire configure
// DO NOT EDIT. Run `flutterfire configure` to regenerate this file.

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'This project is configured for mobile only (Android/iOS).',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'This project is configured for mobile only (Android/iOS).',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxlngoqYTLsqj79AOFUyCFyPYVP_u8M0',
    appId: '1:257422005267:android:2ff6ef1737aee2b1d5dbe6',
    messagingSenderId: '257422005267',
    projectId: 'kigalidirectory-1bdaf',
    storageBucket: 'kigalidirectory-1bdaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEezDPVHhjsoZLi18OCK9m2PNVJXmFKV0',
    appId: '1:257422005267:ios:b2e40771858a7355d5dbe6',
    messagingSenderId: '257422005267',
    projectId: 'kigalidirectory-1bdaf',
    storageBucket: 'kigalidirectory-1bdaf.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

}
